# Imagen base oficial de Node.js
FROM node:latest

# Crear y usar directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar todo el código al contenedor
COPY . .

# Generar el cliente de Prisma
RUN npx prisma generate

# Exponer el puerto que usa tu app
EXPOSE 3000

# Comando de inicio
CMD ["npm", "run", "dev"]
