services:
  db-eventos:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: events_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    restart: always
    depends_on:
      - db-eventos
    environment:
      - DATABASE_URL=mysql://root:rootpass@db-eventos:3306/events_db
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    # ejemplo de comando que espera a que el puerto esté activo antes de ejecutar migraciones
    command: >
      sh -c "\
        until nc -z db-eventos 3306; do echo 'esperando DB...'; sleep 1; done; \
        npx prisma migrate deploy && npm run dev"

volumes:
  mysql_data:
