

services:
   db:
      image: mysql:8.0
      container_name: mysql_db
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: rootpass
         MYSQL_DATABASE: events_db
      ports:
         - '3306:3306'
      volumes:
         - mysql_data:/var/lib/mysql

   app:
      build: .
      container_name: node_app
      restart: always
      depends_on:
         - db
      environment:
         - DATABASE_URL=mysql://root:rootpass@db:3306/events_db
         - JWT_SECRET=${JWT_SECRET}
         - JWT_ALGORITHM=${JWT_ALGORITHM}
         - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
         - PORT=3000
      ports:
         - '3000:3000'
      volumes:
         - .:/app
         - /app/node_modules
      command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
   mysql_data:
