services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d usersdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  usersservice:
    build:
      context: ./UsersService
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: